app/config/routes.rb
Rails.application.routes.draw do

  resources :projects, only: [:index, :show] do
    resources :project_partials, only: [:index]
    end
  resources :project_partials, only: [:show] do
    resources :mep_audios, only: [:index, :new, :create]
  end
  resources :mep_audios, only: [:show, :edit, :update, :destroy]

  root 'projects#index'
end

app/app/controllers/mep_audios_controller.rb
class MepAudiosController < ApplicationController
  def index
    @project_partial = BsagProjectPartial.find(params[:project_partial_id])
    @mep_audios = @project_partial.mep_audios.all
  end

  def show
    @mep_audio = BsagMepAudio.find(params[:id])
  end

  def new
    @mep_audio = BsagMepAudio.new
  end

  def edit
    @mep_audio = BsagMepAudio.find(params[:id])
  end

  def create
    @project_partial = BsagProjectPartial.find(params[:project_partial_id])
    @mep_audio = @project_partial.mep_audios.create(mep_audio_params)
    if @mep_audio.save
      redirect_to project_partial_mep_audios_path
    else
      render 'new'
    end
  end

  def update
    @mep_audio = BsagMepAudio.find(params[:id])
    if @mep_audio.update(mep_audio_params)
      redirect_to project_partial_mep_audios_path(@mep_audio.bsag_project_partial_id)
    else
      render 'edit'
    end
  end

  def destroy
    @mep_audio = BsagMepAudio.find(params[:id])
    @mep_audio.destroy
    redirect_to project_partial_mep_audios_path(@mep_audio.bsag_project_partial_id)
  end

  private

  def mep_audio_params
    params.require(:bsag_mep_audio).permit(:bsag_project_partial_id,
                                           :bsag_audio_type_id,
                                           :receiving_date,
                                           :bsag_mep_version_id,
                                           :version_number,
                                           :version_name_ext,
                                           :bsag_audio_format_id,
                                           :bsag_audio_speed_id,
                                           :is_complete,
                                           :is_complete_comment,
                                           :is_in_sync,
                                           :is_in_sync_comment,
                                           :dbtp_max, :lra, :lufs,
                                           :bsag_channel_error_id,
                                           :channel_error_comment,
                                           :bsag_audio_fault_id,
                                           :audio_fault_comment,
                                           :bsag_mep_evaluation_id)
  end
end

app/app/helpers/mep_audios_helper.rb
module MepAudiosHelper
end

app/app/views/mep_audios/_form.html.haml
- disabled ||= false

= form_for @mep_audio, url: { action: action_name }, html: { class: "form-group" } do |form|
  - if @mep_audio.errors.any?
    .group
      .alert.alert-danger
        %h2
          = pluralize(@mep_audio.errors.count, "errors")
          prohibited this mep from being saved:
        %ul
          - @mep_audio.errors.full_messages.each do |msg|
            %li= msg
  .row
    .group
      .col-xs-12
        .form-group-row
          .col-xs-6.col-md-3
            = form.label :bsag_mep_version_id, "Audiotyp"
            = form.collection_select :bsag_audio_type_id, BsagAudioType.order(:id), :id, :name,
                                     {}, { class: "form-control", disabled: disabled }
        .form-group-row
          .col-xs-6.col-md-3
            = form.label :bsag_audio_format_id, "Audioformat"
            = form.collection_select :bsag_audio_format_id, BsagAudioFormat.order(:id), :id, :name,
                                     {}, { class: "form-control", disabled: disabled }
        .form-group-row
          .col-xs-12.col-md-6
            = form.label :receiving_date, "Eingangsdatum"
            = form.text_field :receiving_date, { class: "form-control", "data-provide" => "datepicker", "data-date-format" => "dd.mm.yyyy", disabled: disabled,
                              value: (@mep_audio.receiving_date ? @mep_audio.receiving_date.strftime("%d.%m.%Y") : Date.today.strftime("%d.%m.%Y")) }
  .row
    .group
      .col-xs-12
        .form-group-row
          .col-xs-6.col-md-3
            = form.label :bsag_mep_version_id, "Audioversion"
            = form.collection_select(:bsag_mep_version_id, BsagMepVersion.order(:id), :id, :name,
                                     {}, { class: "form-control", disabled: disabled })
        .form-group-row
          .col-xs-6.col-md-3
            = form.label :version_number, "Versionsnummer"
            = form.select :version_number, (0..9), {}, { class: "form-control", disabled: disabled }
        .form-group-row
          .col-xs-12.col-md-6
            = form.label :version_name_ext, "Externer Name"
            = form.text_field :version_name_ext, { class: "form-control text_area", disabled: disabled }
  .row
    .group
      .col-xs-12
        .form-group-row
          .col-xs-6.col-md-3
            = form.label :bsag_audio_speed_id, "Geschwindigkeit"
            = form.collection_select :bsag_audio_speed_id, BsagAudioSpeed.order(:id), :id, :speed,
                                     {}, { class: "form-control", disabled: disabled }
        .form-group-row
          .col-xs-6.col-md-3
            = form.label :dbtp_max, "dBTP max"
            = form.text_field :dbtp_max, { class: "form-control text_area", disabled: disabled }
        .form-group-row
          .col-xs-6.col-md-3
            = form.label :lra, "LRA"
            = form.text_field :lra, { class: "form-control text_area", disabled: disabled }
        .form-group-row
          .col-xs-6.col-md-3
            = form.label :lufs, "LUFS"
            = form.text_field :lufs, { class: "form-control text_area", disabled: disabled }
  .row
    .group
      .col-xs-12
        .form-group-row
          .col-xs-12.col-md-3
            = form.label :is_complete, "Vollständig"
            = form.check_box :is_complete, { class: "form-control no-border", disabled: disabled }
        .form-group-row
          .col-xs-12.col-md-9
            = form.label :is_complete_comment, "Kommentar"
            = form.text_area :is_complete_comment, { class: "form-control text_area", disabled: disabled }
  .row
    .group
      .col-xs-12
        .form-group-row
          .col-xs-12.col-md-3
            = form.label :is_in_sync, "Synchron"
            = form.check_box :is_in_sync, { class: "form-control no-border", disabled: disabled }
        .form-group-row
          .col-xs-12.col-md-9
            = form.label :is_in_sync_comment, "Kommentar"
            = form.text_area :is_in_sync_comment, { class: "form-control text_area", disabled: disabled }
  .row
    .group
      .col-xs-12
        .form-group-row
          .col-xs-12.col-md-3
            = form.label :bsag_channel_error_id, "Kanäle"
            = form.collection_select :bsag_channel_error_id, BsagChannelError.order(:id), :id, :name,
                                     {}, { class: "form-control", disabled: disabled }
        .form-group-row
          .col-xs-12.col-md-9
            = form.label :channel_error_comment, "Kommentar"
            = form.text_area :channel_error_comment, { class: "form-control text_area", disabled: disabled }
  .row
    .group
      .col-xs-12
        .form-group-row
          .col-xs-12.col-md-3
            = form.label :bsag_audio_fault_id, "Störung"
            = form.collection_select :bsag_audio_fault_id, BsagAudioFault.order(:id), :id, :name,
                                     {}, { class: "form-control", disabled: disabled }
        .form-group-row
          .col-xs-12.col-md-9
            = form.label :audio_fault_comment, "Kommentar"
            = form.text_area :audio_fault_comment, { class: "form-control text_area", disabled: disabled }
  .row
    .group
      .col-xs-12
        .form-group-row
          .col-xs-12.col-md-3
            = form.label :bsag_mep_evaluation_id, "Bewertung"
            = form.collection_select :bsag_mep_evaluation_id, BsagMepEvaluation.order(:id), :id, :name,
                                     {}, { class: "form-control", disabled: disabled }
        .form-group-row
          .col-xs-12.col-md-9
            %label Änderungen speichen
            = form.button :Speichern, name: :create, class: "btn btn-primary btn-block", disabled: disabled

app/app/views/mep_audios/edit.html.haml
.group
  .h1.text-center Bericht bearbeiten

= render 'form', action_name: "update"

.group
  = link_to 'zurück', project_partial_mep_audios_path(@mep_audio.bsag_project_partial_id)

app/app/views/mep_audios/index.html.haml
.group
  %h1.text-center Materialeingangsprüfungberichte

.group
  %table.table.table-striped
    %thead
      %th Audiotyp
      %th Audioformat
      %th Version
      %th Bewertung
      %th
      %th
      %th
    %tbody
      - @mep_audios.order(:bsag_audio_type_id, :bsag_mep_version_id, :version_number).each do |mep_audio|
        %tr
          %td= mep_audio.audio_type.name
          %td= mep_audio.audio_format.name
          %td #{mep_audio.mep_version.name} #{mep_audio.version_number}
          %td= mep_audio.evaluation.name
          %td= link_to 'Anzeigen', mep_audio_path(mep_audio)
          %td= link_to 'Bearbeiten', edit_mep_audio_path(mep_audio)
          %td= link_to 'Löschen', mep_audio_path(mep_audio), method: :delete, data: { confirm: 'Are you sure?' }

.group
  .text-right= link_to 'Neuer Bericht', new_project_partial_mep_audio_path(@project_partial)

app/app/views/mep_audios/new.html.haml
.group
  .h1.text-center Bericht erstellen

= render 'form', action_name: "create"

.group
  = link_to 'zurück', project_partial_mep_audios_path

app/app/views/mep_audios/show.html.haml
.group
  .h1.text-center
    Bericht anzeigen

= render 'form', action_name: "update", disabled: true

.group
  = link_to 'zurück', project_partial_mep_audios_path(@mep_audio.bsag_project_partial_id)